# crawler config
agent_name : 'your-agent-name'

# mongodb config
mongo_host : 'localhost'
mongo_port : 27017
mongo_dbname : 'pixiv'

# pixiv config
pixiv_user : 'your-name'
pixiv_pass : 'your-passwd'

interval : 30
error_limit : 10
